# Generated by Django 5.1.1 on 2025-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='negative_marking',
            field=models.FloatField(default=0, help_text='Specify the negative marking value for incorrect answers. Default is 0 (no negative marking).'),
        ),
    ]
