# Generated by Django 5.1.1 on 2025-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizattempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='access_mode',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50),
        ),
    ]
