# Generated by Django 5.1.1 on 2025-04-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_category_access_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='questions',
            field=models.ManyToManyField(related_name='items', to='quiz.question'),
        ),
    ]
