# Generated by Django 5.2.5 on 2025-09-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Main banner image representing the tournament.', null=True, upload_to='tournaments/banners/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short tagline or subtitle for the tournament.', max_length=255, null=True),
        ),
    ]
