# Generated by Django 5.1.1 on 2025-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpenAccount',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=255, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('limited', 'Limited'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('removed', 'Removed')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'tbl_user_open_account',
            },
        ),
    ]
