# Generated by Django 5.1.1 on 2025-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useropenaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useropenaccount',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
