# Generated by Django 5.1.1 on 2025-04-23 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useropenaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropenaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
